apiVersion: v1
kind: ServiceAccount
metadata:
  name: steamroller
  namespace: default
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: steamroller-psp
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'emptyDir'
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: steamroller
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - steamroller-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: steamroller
subjects:
- kind: ServiceAccount
  name: steamroller
  namespace: default
roleRef:
  kind: ClusterRole
  name: steamroller-psp
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steamroller
  labels:
    app: steamroller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steamroller
  template:
    metadata:
      labels:
        app: steamroller
    spec:
      serviceAccountName: steamroller
      securityContext:
        runAsUser: 1000
      containers:
      - name: steamroller
        image: tuommaki/steamroller:latest
        args: ["-filename /data/test-*.data"]
        volumeMounts:
        - mountPath: /data
          name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}
